#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo -n "From SDCard (0) or QSPI (1) ? "

if read -t 2 choice; then
    if [ $choice -eq 0 ] 
    then
        bootgen -image boot_builder.bif -w -o BOOT.bin 2> /dev/null
        if [ $? -ne 0 ] 
        then
            echo -e "${RED}Error no bootgen command${NC}" 
            exit
        fi
        echo -e "${GREEN}SDCARD bin image created!${NC}"
    elif [ $choice -eq 1 ] 
    then
        bootgen -image qspi_boot_builder.bif -w -o BOOT.mcs
        if [ $? -ne 0 ] 
        then
            echo -e "${RED}Error no bootgen command${NC}" 
            exit
        fi
        echo -e "${GREEN}QSPI mcs image created!${NC}"
    else
        echo -e "${RED}Wrong choice${NC}"
    fi
else
        bootgen -image boot_builder.bif -w -o BOOT.bin
        echo
        echo -e "${GREEN}SDCARD bin image created!${NC}"
fi
